language:
 - c
os:
 - linux
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty universe"
 - sudo apt-get -qq update
install:
 - sudo apt-get install -y libuv-dev libjack-dev libasound2-dev librtmidi-dev libluajit-5.1-dev libeina-dev
before_script:
 - mkdir build
 - cd build
 - cmake -DUSE_RTMIDI=0 ..
script:
 - make
